sudo:
  false

language:
  python

python:
  - 2.7

services:
  - docker

install:
  - make install

script:
  - make build
  - make test
  - make push

deploy:
  - provider: script
    script: make deploy
    on:
      branch: master
