actrn:
  extends:
    service: actrn
    file: docker-cloud.yml

euctr:
  extends:
    service: euctr
    file: docker-cloud.yml

fdadl:
  extends:
    service: fdadl
    file: docker-cloud.yml

gsk:
  extends:
    service: gsk
    file: docker-cloud.yml

icdcm:
  extends:
    service: icdcm
    file: docker-cloud.yml

icdpcs:
  extends:
    service: icdpcs
    file: docker-cloud.yml

ictrp:
  extends:
    service: ictrp
    file: docker-cloud.yml

isrctn:
  extends:
    service: isrctn
    file: docker-cloud.yml

jprn:
  extends:
    service: jprn
    file: docker-cloud.yml

nct:
  extends:
    service: nct
    file: docker-cloud.yml

pfizer:
  extends:
    service: pfizer
    file: docker-cloud.yml

pubmed:
  extends:
    service: pubmed
    file: docker-cloud.yml

takeda:
  extends:
    service: takeda
    file: docker-cloud.yml
